# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clustermap.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvas, NavigationToolbar2QT as NavigationToolbar
from matplotlib.figure import Figure
import seaborn as sns


class Ui_Form(object):
    def setupUi(self, Form, df):
        self.df = df
        Form.setObjectName("Spatial correlation analysis")
        Form.resize(747, 624)
        Form.setStyleSheet("background-color: rgb(160, 160, 160);")
        Form.setWindowFlags(Form.windowFlags() | QtCore.Qt.WindowMaximizeButtonHint | QtCore.Qt.WindowMinimizeButtonHint)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        x = sns.clustermap(self.df, metric="correlation", square=True, yticklabels=True, xticklabels=True)
        canvas = FigureCanvas(x.figure)
        self.toolbar = NavigationToolbar(canvas)
        self.gridLayout.addWidget(self.toolbar)
        canvas.draw()
        self.gridLayout.addWidget(canvas)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Correlation map"))
        Form.setWindowIcon(QtGui.QIcon('msipixel_icon_exe.ico'))