# -*- coding: utf-8 -*-
"""
Created on Thu Nov 10 14:51:21 2022

@author: Giuseppe Martano
"""


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(900, 600)
        MainWindow.setMinimumSize(QtCore.QSize(900, 600))
        MainWindow.setMaximumSize(QtCore.QSize(900, 600))
        font = QtGui.QFont()
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAcceptDrops(False)
        MainWindow.setStatusTip("")
        MainWindow.setStyleSheet("")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("background-color: rgb(160, 160, 160);")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_file_selection = QtWidgets.QFrame(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.frame_file_selection.setFont(font)
        self.frame_file_selection.setStyleSheet("")
        self.frame_file_selection.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_file_selection.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_file_selection.setObjectName("frame_file_selection")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_file_selection)
        self.horizontalLayout.setContentsMargins(12, 0, 12, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_load_mzml = QtWidgets.QPushButton(self.frame_file_selection)
        self.button_load_mzml.setMinimumSize(QtCore.QSize(100, 0))
        self.button_load_mzml.setMaximumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.button_load_mzml.setFont(font)
        self.button_load_mzml.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_load_mzml.setStyleSheet("")
        self.button_load_mzml.setObjectName("button_load_mzml")
        self.horizontalLayout.addWidget(self.button_load_mzml)
        self.textEdit_mzml = QtWidgets.QTextEdit(self.frame_file_selection)
        self.textEdit_mzml.setEnabled(False)
        self.textEdit_mzml.setMinimumSize(QtCore.QSize(1, 0))
        self.textEdit_mzml.setMaximumSize(QtCore.QSize(200, 30))
        self.textEdit_mzml.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_mzml.setObjectName("textEdit_mzml")
        self.horizontalLayout.addWidget(self.textEdit_mzml)
        self.button_load_xml = QtWidgets.QPushButton(self.frame_file_selection)
        self.button_load_xml.setMinimumSize(QtCore.QSize(100, 0))
        self.button_load_xml.setMaximumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.button_load_xml.setFont(font)
        self.button_load_xml.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_load_xml.setAutoFillBackground(False)
        self.button_load_xml.setStyleSheet("")
        self.button_load_xml.setObjectName("button_load_xml")
        self.horizontalLayout.addWidget(self.button_load_xml)
        self.textEdit_xml = QtWidgets.QTextEdit(self.frame_file_selection)
        self.textEdit_xml.setEnabled(False)
        self.textEdit_xml.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_xml.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_xml.setObjectName("textEdit_xml")
        self.horizontalLayout.addWidget(self.textEdit_xml)
        self.button_load_folder = QtWidgets.QPushButton(self.frame_file_selection)
        self.button_load_folder.setMinimumSize(QtCore.QSize(180, 30))
        self.button_load_folder.setMaximumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.button_load_folder.setFont(font)
        self.button_load_folder.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_load_folder.setStyleSheet("")
        self.button_load_folder.setObjectName("button_load_folder")
        self.horizontalLayout.addWidget(self.button_load_folder)
        self.textEdit_folder = QtWidgets.QTextEdit(self.frame_file_selection)
        self.textEdit_folder.setEnabled(False)
        self.textEdit_folder.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_folder.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_folder.setObjectName("textEdit_folder")
        self.horizontalLayout.addWidget(self.textEdit_folder)
        self.verticalLayout_2.addWidget(self.frame_file_selection)
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(3)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(12, 8, 12, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setKerning(True)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 0));\n"
"border-radius : 0;\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_4.setCursorPosition(5)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_3.addWidget(self.lineEdit_4)
        self.frame_14 = QtWidgets.QFrame(self.frame_2)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 170))
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 170))
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_5 = QtWidgets.QFrame(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 126))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 126))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setContentsMargins(4, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_parallel = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_parallel.setEnabled(True)
        self.checkBox_parallel.setMinimumSize(QtCore.QSize(0, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.checkBox_parallel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.checkBox_parallel.setFont(font)
        self.checkBox_parallel.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(0, 0, 0);\n"
"")
        self.checkBox_parallel.setObjectName("checkBox_parallel")
        self.verticalLayout_4.addWidget(self.checkBox_parallel)
        self.checkBox_norm = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_norm.setEnabled(True)
        self.checkBox_norm.setMinimumSize(QtCore.QSize(0, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.checkBox_norm.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.checkBox_norm.setFont(font)
        self.checkBox_norm.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(0, 0, 0);\n"
"")
        self.checkBox_norm.setChecked(True)
        self.checkBox_norm.setObjectName("checkBox_norm")
        self.verticalLayout_4.addWidget(self.checkBox_norm)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setMaximumSize(QtCore.QSize(35, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(255, 255, 255);\n"
"border-radius : 0;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.ppm_spinBox = QtWidgets.QSpinBox(self.frame_6)
        self.ppm_spinBox.setMinimumSize(QtCore.QSize(120, 20))
        self.ppm_spinBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ppm_spinBox.setObjectName("ppm_spinBox")
        self.horizontalLayout_3.addWidget(self.ppm_spinBox)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.verticalLayout_11.addWidget(self.frame_5)
        self.pushButton_inf_process = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_inf_process.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_inf_process.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.pushButton_inf_process.setFont(font)
        self.pushButton_inf_process.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_inf_process.setStyleSheet("")
        self.pushButton_inf_process.setObjectName("pushButton_inf_process")
        self.verticalLayout_11.addWidget(self.pushButton_inf_process)
        self.verticalLayout_3.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_2)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 130))
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.checkBox_inf1 = QtWidgets.QCheckBox(self.frame_15)
        self.checkBox_inf1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_inf1.sizePolicy().hasHeightForWidth())
        self.checkBox_inf1.setSizePolicy(sizePolicy)
        self.checkBox_inf1.setMinimumSize(QtCore.QSize(0, 20))
        self.checkBox_inf1.setMaximumSize(QtCore.QSize(16777215, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.checkBox_inf1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setKerning(True)
        self.checkBox_inf1.setFont(font)
        self.checkBox_inf1.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(0, 0, 0);\n"
"")
        self.checkBox_inf1.setObjectName("checkBox_inf1")
        self.verticalLayout_12.addWidget(self.checkBox_inf1)
        self.progressBar = QtWidgets.QProgressBar(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 10))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_12.addWidget(self.progressBar)
        self.checkBox_inf2 = QtWidgets.QCheckBox(self.frame_15)
        self.checkBox_inf2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_inf2.sizePolicy().hasHeightForWidth())
        self.checkBox_inf2.setSizePolicy(sizePolicy)
        self.checkBox_inf2.setMinimumSize(QtCore.QSize(0, 20))
        self.checkBox_inf2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setKerning(True)
        self.checkBox_inf2.setFont(font)
        self.checkBox_inf2.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(0, 0, 0);")
        self.checkBox_inf2.setObjectName("checkBox_inf2")
        self.verticalLayout_12.addWidget(self.checkBox_inf2)
        self.progressBar_2 = QtWidgets.QProgressBar(self.frame_15)
        self.progressBar_2.setMinimumSize(QtCore.QSize(0, 10))
        self.progressBar_2.setMaximumSize(QtCore.QSize(16777215, 10))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.verticalLayout_12.addWidget(self.progressBar_2)
        self.checkBox_inf3 = QtWidgets.QCheckBox(self.frame_15)
        self.checkBox_inf3.setEnabled(False)
        self.checkBox_inf3.setMinimumSize(QtCore.QSize(0, 20))
        self.checkBox_inf3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setKerning(True)
        self.checkBox_inf3.setFont(font)
        self.checkBox_inf3.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(0, 0, 0);")
        self.checkBox_inf3.setObjectName("checkBox_inf3")
        self.verticalLayout_12.addWidget(self.checkBox_inf3)
        self.progressBar_3 = QtWidgets.QProgressBar(self.frame_15)
        self.progressBar_3.setMinimumSize(QtCore.QSize(0, 10))
        self.progressBar_3.setMaximumSize(QtCore.QSize(16777215, 10))
        self.progressBar_3.setStyleSheet("")
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setObjectName("progressBar_3")
        self.verticalLayout_12.addWidget(self.progressBar_3)
        self.verticalLayout_3.addWidget(self.frame_15)
        self.frame_13 = QtWidgets.QFrame(self.frame_2)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_inf_explore = QtWidgets.QPushButton(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_inf_explore.sizePolicy().hasHeightForWidth())
        self.pushButton_inf_explore.setSizePolicy(sizePolicy)
        self.pushButton_inf_explore.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_inf_explore.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.pushButton_inf_explore.setFont(font)
        self.pushButton_inf_explore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_inf_explore.setStyleSheet("")
        self.pushButton_inf_explore.setObjectName("pushButton_inf_explore")
        #self.verticalLayout_10.addWidget(self.pushButton_inf_explore)
        self.pushButton_manual = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_manual.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.pushButton_manual.setFont(font)
        self.pushButton_manual.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_manual.setStyleSheet("")
        self.pushButton_manual.setObjectName("pushButton_manual")
        self.verticalLayout_10.addWidget(self.pushButton_manual)
        self.verticalLayout_3.addWidget(self.frame_13)
        self.widget_2 = QtWidgets.QWidget(self.frame_2)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 19))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 19))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3.addWidget(self.widget_2)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(3)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(12, 8, 12, 0)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setKerning(True)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 0));\n"
"border-radius : 0;\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_5.setCursorPosition(5)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setDragEnabled(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_5.addWidget(self.lineEdit_5)
        self.frame_16 = QtWidgets.QFrame(self.frame_3)
        self.frame_16.setMinimumSize(QtCore.QSize(0, 170))
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 170))
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_7 = QtWidgets.QFrame(self.frame_16)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 126))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 126))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setContentsMargins(4, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(255, 255, 255);\n"
"border-radius : 0;\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_4.addWidget(self.lineEdit_2)
        self.spinBox_2_thr = QtWidgets.QSpinBox(self.frame_8)
        self.spinBox_2_thr.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_2_thr.setObjectName("spinBox_2_thr")
        self.horizontalLayout_4.addWidget(self.spinBox_2_thr)
        self.verticalLayout_7.addWidget(self.frame_8)
        self.frame_10 = QtWidgets.QFrame(self.frame_7)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(255, 255, 255);\n"
"border-radius : 0;\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_5.addWidget(self.lineEdit_3)
        self.spinBox_pixel = QtWidgets.QSpinBox(self.frame_10)
        self.spinBox_pixel.setMinimumSize(QtCore.QSize(90, 0))
        self.spinBox_pixel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_pixel.setObjectName("spinBox_pixel")
        self.horizontalLayout_5.addWidget(self.spinBox_pixel)
        self.verticalLayout_7.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(255, 255, 255);\n"
"border-radius : 0;\n"
"")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_6.addWidget(self.lineEdit_7)
        self.spinBox_pixel_2 = QtWidgets.QSpinBox(self.frame_9)
        self.spinBox_pixel_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_pixel_2.setObjectName("spinBox_pixel_2")
        self.horizontalLayout_6.addWidget(self.spinBox_pixel_2)
        self.verticalLayout_7.addWidget(self.frame_9)
        self.verticalLayout_13.addWidget(self.frame_7)
        self.pushButton_spat_process_2 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_spat_process_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_spat_process_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.pushButton_spat_process_2.setFont(font)
        self.pushButton_spat_process_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_spat_process_2.setStyleSheet("")
        self.pushButton_spat_process_2.setObjectName("pushButton_spat_process_2")
        self.verticalLayout_13.addWidget(self.pushButton_spat_process_2)
        self.verticalLayout_5.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.frame_3)
        self.frame_17.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_17.setMaximumSize(QtCore.QSize(16777215, 90))
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_12 = QtWidgets.QFrame(self.frame_17)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 41))
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.checkBox_spat = QtWidgets.QCheckBox(self.frame_12)
        self.checkBox_spat.setEnabled(False)
        self.checkBox_spat.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setKerning(True)
        self.checkBox_spat.setFont(font)
        self.checkBox_spat.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(0, 0, 0);\n"
"")
        self.checkBox_spat.setObjectName("checkBox_spat")
        self.verticalLayout_9.addWidget(self.checkBox_spat)
        self.progressBar_spat = QtWidgets.QProgressBar(self.frame_12)
        self.progressBar_spat.setMinimumSize(QtCore.QSize(0, 10))
        self.progressBar_spat.setMaximumSize(QtCore.QSize(16777215, 10))
        self.progressBar_spat.setProperty("value", 24)
        self.progressBar_spat.setObjectName("progressBar_spat")
        self.verticalLayout_9.addWidget(self.progressBar_spat)
        self.verticalLayout_14.addWidget(self.frame_12)
        self.verticalLayout_5.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.frame_3)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pushButton_rgb_2 = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_rgb_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_rgb_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.pushButton_rgb_2.setFont(font)
        self.pushButton_rgb_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_rgb_2.setStyleSheet("")
        self.pushButton_rgb_2.setObjectName("pushButton_rgb_2")
        self.verticalLayout_15.addWidget(self.pushButton_inf_explore)
        self.verticalLayout_15.addWidget(self.pushButton_rgb_2)
        self.pushButton_spat_explore_2 = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_spat_explore_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_spat_explore_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.pushButton_spat_explore_2.setFont(font)
        self.pushButton_spat_explore_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_spat_explore_2.setStyleSheet("")
        self.pushButton_spat_explore_2.setObjectName("pushButton_spat_explore_2")
        self.verticalLayout_15.addWidget(self.pushButton_spat_explore_2)
        self.pushButton_rgb = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_rgb.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_rgb.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.pushButton_rgb.setFont(font)
        self.pushButton_rgb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_rgb.setStyleSheet("")
        self.pushButton_rgb.setObjectName("pushButton_rgb")
        self.verticalLayout_15.addWidget(self.pushButton_rgb)
        self.verticalLayout_5.addWidget(self.frame_18)
        self.frame_11 = QtWidgets.QFrame(self.frame_3)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 19))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 15))
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_5.addWidget(self.frame_11)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(3)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setContentsMargins(12, 8, 12, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setKerning(True)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 0));\n"
"border-radius : 0;\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_6.addWidget(self.lineEdit_6)
        self.frame_19 = QtWidgets.QFrame(self.frame_4)
        self.frame_19.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_19.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.pushButton_hmdb = QtWidgets.QPushButton(self.frame_19)
        self.pushButton_hmdb.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_hmdb.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        self.pushButton_hmdb.setFont(font)
        self.pushButton_hmdb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_hmdb.setStyleSheet("")
        self.pushButton_hmdb.setObjectName("pushButton_hmdb")
        self.verticalLayout_16.addWidget(self.pushButton_hmdb)
        self.verticalLayout_6.addWidget(self.frame_19)
        self.frame_20 = QtWidgets.QFrame(self.frame_4)
        self.frame_20.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.checkBox_hmdb = QtWidgets.QCheckBox(self.frame_20)
        self.checkBox_hmdb.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setKerning(True)
        self.checkBox_hmdb.setFont(font)
        self.checkBox_hmdb.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(0, 0, 0);\n"
"")
        self.checkBox_hmdb.setObjectName("checkBox_hmdb")
        self.verticalLayout_17.addWidget(self.checkBox_hmdb)
        self.progressBar_spat_2 = QtWidgets.QProgressBar(self.frame_20)
        self.progressBar_spat_2.setProperty("value", 24)
        self.progressBar_spat_2.setObjectName("progressBar_spat_2")
        self.verticalLayout_17.addWidget(self.progressBar_spat_2)
        self.checkBox_hmdb1 = QtWidgets.QCheckBox(self.frame_20)
        self.checkBox_hmdb1.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setKerning(True)
        self.checkBox_hmdb1.setFont(font)
        self.checkBox_hmdb1.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(0, 0, 0);\n"
"")
        self.checkBox_hmdb1.setObjectName("checkBox_hmdb1")
        self.verticalLayout_17.addWidget(self.checkBox_hmdb1)
        self.progressBar_spat_3 = QtWidgets.QProgressBar(self.frame_20)
        self.progressBar_spat_3.setProperty("value", 24)
        self.progressBar_spat_3.setObjectName("progressBar_spat_3")
        self.verticalLayout_17.addWidget(self.progressBar_spat_3)
        self.verticalLayout_6.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.frame_4)
        self.frame_21.setMinimumSize(QtCore.QSize(0, 190))
        self.frame_21.setMaximumSize(QtCore.QSize(16777215, 190))
        self.frame_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_6.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.frame_4)
        self.frame_22.setMinimumSize(QtCore.QSize(0, 90))
        self.frame_22.setMaximumSize(QtCore.QSize(16777215, 95))
        self.frame_22.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.pushButton = QtWidgets.QPushButton(self.frame_22)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_18.addWidget(self.pushButton)
        self.verticalLayout_6.addWidget(self.frame_22)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_mzML_file = QtWidgets.QAction(MainWindow)
        self.actionLoad_mzML_file.setObjectName("actionLoad_mzML_file")
        self.actionLoad_XML_file = QtWidgets.QAction(MainWindow)
        self.actionLoad_XML_file.setObjectName("actionLoad_XML_file")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MSIpixel"))
        MainWindow.setWindowIcon(QtGui.QIcon('msipixel_icon_exe.ico'))
        self.button_load_mzml.setText(_translate("MainWindow", "Load mzML"))
        self.textEdit_mzml.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:9.75pt;\"><br /></p></body></html>"))
        self.button_load_xml.setText(_translate("MainWindow", "Load XML"))
        self.textEdit_xml.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:9.75pt;\"><br /></p></body></html>"))
        self.button_load_folder.setText(_translate("MainWindow", "Load Library Folder"))
        self.textEdit_folder.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:9.75pt;\"><br /></p></body></html>"))
        self.lineEdit_4.setText(_translate("MainWindow", "Analysis"))
        self.checkBox_parallel.setText(_translate("MainWindow", "Parallel acquisition"))
        self.checkBox_norm.setText(_translate("MainWindow", "Normalize by TIC"))
        self.lineEdit.setText(_translate("MainWindow", "ppm"))
        self.pushButton_inf_process.setText(_translate("MainWindow", "Process"))
        self.checkBox_inf1.setText(_translate("MainWindow", "  Extract MS1 and MS2"))
        self.checkBox_inf2.setText(_translate("MainWindow", "  Annonate MS2 Spectra"))
        self.checkBox_inf3.setText(_translate("MainWindow", "  Consolidate annotation"))
        self.pushButton_inf_explore.setText(_translate("MainWindow", "Explore results"))
        self.pushButton_manual.setText(_translate("MainWindow", "Manual Inspection"))
        self.lineEdit_5.setText(_translate("MainWindow", "Stats"))
        self.lineEdit_2.setText(_translate("MainWindow", "Threshold"))
        self.lineEdit_3.setText(_translate("MainWindow", "Perc. of pixel"))
        self.lineEdit_7.setText(_translate("MainWindow", "MS2 score (%)"))
        self.pushButton_spat_process_2.setText(_translate("MainWindow", "Filter"))
        self.checkBox_spat.setText(_translate("MainWindow", " Calculate spatial differences"))
        self.pushButton_rgb_2.setText(_translate("MainWindow", "Pixel analysis"))
        self.pushButton_spat_explore_2.setText(_translate("MainWindow", "Spatial correlation"))
        self.pushButton_rgb.setText(_translate("MainWindow", "RGB Plot"))
        self.lineEdit_6.setText(_translate("MainWindow", "Tools"))
        self.pushButton_hmdb.setText(_translate("MainWindow", "HMDB easy parser"))
        self.checkBox_hmdb.setText(_translate("MainWindow", " Getting HMDB compounds"))
        self.checkBox_hmdb1.setText(_translate("MainWindow", " Adding MS/MS data"))
        self.pushButton.setText(_translate("MainWindow", "Help"))
        self.actionLoad_mzML_file.setText(_translate("MainWindow", "Load mzML file"))
        self.actionLoad_XML_file.setText(_translate("MainWindow", "Load XML file"))